{include file="/common/header-1.tpl" nocache}

{$static_page.content}

{* <div class="home-container static-cont">
    <section class="clearfix ">
        <div class="container">
            <div class="tbcon-wrap">
                <h1><u>HEMPBUYER AFFILIATE REFERRAL AGREEMENT</u></h1>
            </div>
        </div>
    </section>
    <section class="about-us">
        <div class="container" style="margin-top: 0;">
            <div class="media">
            <div class="media-body" style="padding:0">
            
            <p>This HempBuyer Affiliate Referral Agreement (this “Agreement”) is entered into by 1 Lucky Dog, LLC, a Delaware limited liability company doing business as HempBuyer (“HempBuyer”), whose principal place of business is located at 555 N. El Camino Real #A182, San Clemente, California 92672, and [<i style="background-color: yellow;">name of affiliate and, if applicable, type of entity</i>] (“Affiliate”), whose address for business purposes is [<i style="background-color: yellow;">business or home address of affiliate</i>].  HempBuyer and Affiliate (hereinafter collectively, the “Parties” and each a “Party”) have entered into this Agreement based on the following facts:</p>

            <h3 class="text-center"><u>RECITALS</u></h3>
            <p class="pl-5 pr-5">A. &nbsp;	HempBuyer is in the business of, inter alia, connecting buyers and sellers of industrial hemp through an online auction and marketplace website known as hempbuyer.com (the “<u>HempBuyer Website</u>”) to facilitate purchase and sales transactions involving industrial hemp;</p>
            <p class="pl-5 pr-5">B. &nbsp;	Affiliate currently has contacts and relationships with persons and entities that purchase industrial hemp (collectively, “<u>Prospective Buyers</u>”), and expects to have more of such contacts and relationships with Prospective Buyers after entry into this Agreement;</p>
            <p class="pl-5 pr-5">C. &nbsp;	Affiliate desires to refer Prospective Buyers to HempBuyer, and HempBuyer desires to compensate Affiliate for making such referrals on a “commissions-only” basis; and</p>
            <p class="pl-5 pr-5">D. &nbsp;	The Parties desire to document the terms and conditions under which Affiliate will make such referrals and how Affiliate will be compensated therefor.</p>

            <p>NOW THEREFORE, in consideration of the promises hereof and of the mutual promises and agreements contained herein, the Parties hereto, intending to be legally bound, do hereby agree as follows:</p>

            <h3><u>TERMS AND CONDITIONS</u></h3>

            <p>1. &nbsp;	<b><u>Referrals.</u></b>  Affiliate shall refer Prospective Buyers through one or both of the following methods:</p>
            <p class="pl-5 pr-5">a. &nbsp;	<b><u>Click-Through Referrals</u></b>.  If Affiliate has a website or other online portal on which Affiliate displays digital advertisements (the “<u>Affiliate Website</u>”), then Affiliate may place a “banner” or other similar advertisement on its Affiliate Website, subject to HempBuyer’s prior written approval, that, when “clicked on” by a user of the Affiliate Website, the user will be redirected to “land” on the HempBuyer Website.  HempBuyer shall provide Affiliate with any digital artwork that HempBuyer requires to be displayed by Affiliate in making any banner or similar advertisement to be displayed on the Affiliate Website.  Referrals made under this sub-section will be known as “<u>Click-Through Referrals</u>.”</p>
            <p class="pl-5 pr-5">b. &nbsp;	<b><u>Direct Referrals.</u></b>  Affiliate may also direct Prospective Buyers to register as a “Buyer” on the HempBuyer Website and have such Prospective Buyers acknowledge on their registration documentation to HempBuyer that the Prospective Buyer was referred to either HempBuyer or the HempBuyer Website by Affiliate, which will require the name and email of Affiliate.  Referrals made under this sub-section will be known as “Direct Referrals.”</p>

            <p>2. &nbsp;	<b><u>Compensation.</u></b></p>
            <p class="pl-5 pr-5">a. &nbsp;	Once a Prospective Buyer “clicks through” to the HempBuyer Website through a Click-Through Referral, or registers as a “Buyer” on the HempBuyer Website though a Direct Referral, HempBuyer will track all purchase transactions conducted by the Prospective Buyer at which the Prospective Buyer shall be deemed an “Affiliate Referred Registered Buyer.”</p>
            <p class="pl-5 pr-5">b. &nbsp;	HempBuyer shall pay compensation to Affiliate on a “commission-only” basis.  Affiliate shall receive a commission equal to ten percent (10%) of HempBuyer’s net revenue received from all completed sales conducted by any Affiliate Referred Registered Buyer in the period of one (1) year from the time the Prospective Buyer becomes an Affiliate Referred Registered Buyer.  A sale is “completed” when HempBuyer receives its fees from the parties to the relevant sales transaction.</p>
            <p class="pl-5 pr-5">c. &nbsp;	Not less than once per financial quarter, HempBuyer shall remit all commissions that Affiliate has earned within thirty (30) days prior to the expiration of the financial quarter.  Payment shall be made by check to Affiliate at the address listed in this Agreement.</p>

            <p>3. &nbsp;	<b><u>Independent Contractor Relationship.</u></b></p>
            <p class="pl-5 pr-5">a. &nbsp;	Once a Prospective Buyer “clicks through” to the HempBuyer Website through a Click-Through Referral, or registers as a “Buyer” on the HempBuyer Website though a Direct Referral, HempBuyer will track all purchase transactions conducted by the Prospective Buyer at which the Prospective Buyer shall be deemed an “Affiliate Referred Registered Buyer.”</p>
            <p class="pl-5 pr-5">b. &nbsp;	HempBuyer shall pay compensation to Affiliate on a “commission-only” basis.  Affiliate shall receive a commission equal to ten percent (10%) of HempBuyer’s net revenue received from all completed sales conducted by any Affiliate Referred Registered Buyer in the period of one (1) year from the time the Prospective Buyer becomes an Affiliate Referred Registered Buyer.  A sale is “completed” when HempBuyer receives its fees from the parties to the relevant sales transaction.</p>
            <p class="pl-5 pr-5">c. &nbsp;	Not less than once per financial quarter, HempBuyer shall remit all commissions that Affiliate has earned within thirty (30) days prior to the expiration of the financial quarter.  Payment shall be made by check to Affiliate at the address listed in this Agreement.</p>

            <p class="pl-5 pr-5">a. &nbsp;	Affiliate represents that it is engaged in an independent calling and has complied with all local, state, and federal laws regarding business permits and licenses that may be required to carry out the independent calling and to perform the services to be performed under this Agreement.  Affiliate represents that it is engaged in the same or similar activities for others and that HempBuyer is not Affiliate’s sole client or customer.</p>
            <p class="pl-5 pr-5">b. &nbsp;	Aside from HempBuyer approving any banners or digital advertisements on the Affiliate Website, which Affiliate acknowledges is necessary for protecting the goodwill and reputation of HempBuyer, Affiliate retains the sole right to control or direct the manner in which to make the referrals of the Prospective Buyers are stated herein.</p>
            <p class="pl-5 pr-5">c. &nbsp;	Aside from digital artwork supplied by HempBuyer, Affiliate will supply all equipment, tools, materials, and supplies necessary to make the referrals of the Prospective Buyers under this Agreement.</p>
            <p class="pl-5 pr-5">d. &nbsp;	HempBuyer will not reimburse Affiliate for any expenses incurred by Affiliate as a result of making referrals under this Agreement, including, but not limited to, Affiliate Website-related expenses, telephone expenses, and expenses related to the generation of additional contacts and relationships with Prospective Buyers.  Affiliate is solely responsible for these expenses.</p>
            <p class="pl-5 pr-5">e. &nbsp;	Affiliate may or may not, as Affiliate so chooses, retain employees or assistants to assist Affiliate. HempBuyer is not responsible for the compensation or instruction of Affiliate’s employees or assistants and these employees or assistants remain the sole responsibility of Affiliate.</p>
            <p class="pl-5 pr-5">f. &nbsp;	Affiliate agrees that it is Affiliate’s exclusive responsibility to provide all employment taxes, insurance premiums, and local, state, and federal taxes related to this Agreement. Neither FICA (Social Security), FUTA (Federal Employment), nor local, state, or federal income taxes will be withheld from payments to Affiliate from HempBuyer.</p>

            <p>4. &nbsp;	<b><u>Term and Termination.</u></b>  The term of this Agreement (the “Term”) shall commence on the date set forth above and shall continue for the 12-month period, subject to the termination rights of the Parties as set forth below. This Agreement may be terminated at any time by either Party, without cause, upon thirty (30) days written notice to the other Party. In the event of such termination, Affiliate shall be entitled to commissions on Affiliate Referred Registered Buyers referred to HempBuyer as of the date of the notice.</p>
            <p>5. &nbsp;	<b><u>Indemnification.</u></b>  Affiliate shall defend, indemnify and hold harmless HempBuyer from and against any and all damage, cost, liability, and expense whatsoever (including attorney's fees and related disbursements) incurred by reason of: (a) any failure by Affiliate to perform any covenant or agreement of Affiliate  set forth herein; or (ii) any breach by Affiliate of any representation, warranty, covenant or agreement contained herein. HempBuyer shall have the right to offset against any fees or commissions due Affiliate for any damage, cost, liability, expense, fee or other disbursement incurred by HempBuyer pursuant to this section.</p>
            
            <p>6. &nbsp;	<b><u>Disputes.</u></b></p>
            <p class="pl-5 pr-5">a. &nbsp;	<b><u>Dispute.</u></b>  If any dispute, difference or claim arises out of or in connection with this Agreement, or the subject matter of this Agreement one party may give notice to the other party of the dispute (a “Dispute”), upon which the Parties will attempt to resolve the Dispute between them.</p>

            <p class="pl-5 pr-5">b. &nbsp;	<b><u>Mediation and Arbitration.</u></b>  If the Parties cannot resolve the Dispute within a reasonable period of the date of HempBuyer’s receipt of a written notice describing the Dispute (the “Dispute Notice”), then the following procedures will apply.  Any dispute, claim or controversy arising out of or relating to this Agreement or the breach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by arbitration in Irvine, California before one arbitrator. The arbitration shall be administered by JAMS pursuant to its Comprehensive Arbitration Rules and Procedures. Judgment on the award may be entered in any court having jurisdiction. This clause shall not preclude Parties from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction.  As a condition precedent to arbitration, the Parties must participate in mediation. Should any Party refuse to fully participate or neglect to appear for mediation, they will be barred from maintaining a claim or set-off against the other in arbitration.  Any Party who refuses to appear or participate in the arbitration proceedings will be subject to default. Thirty days prior to the date set for the mediation, the Parties shall make a good faith exchange of any and all documents, photographs, videos, etc., relating to the controversy between them. The mediator, in his or her sole discretion, shall have the power to order additional discovery of any sort allowed under California Law. The mediator may also hire independent experts to assist the mediation process. The costs of mediation, including experts, shall be borne equally by the Parties. To the full extent permitted by applicable law, the Parties hereby waives the right to trial by jury in connection with any such legal action related to this Agreement.  The prevailing Party in any action or proceeding arising out of or to enforce any provision of this Agreement will be awarded reasonable attorneys’ fees and costs incurred in that action or proceeding, or in the enforcement of any judgment or award rendered.</p>
            
            

            <p>7. &nbsp;	<b><u>Governing Law.</u></b>  This Agreement is entered into and intended to be performed in the County of Orange, State of California and shall be governed by, and its terms and conditions shall be construed and enforced in accordance with, the domestic laws of the State of California, excluding conflict of laws principles.</p>

            <p>8. &nbsp;	<b><u>Assignment.</u></b>  Neither this Agreement nor any money due or to become due hereunder may be assigned, in whole or in part, by Affiliate without the prior written consent of HempBuyer, which consent may be withheld in HempBuyer’s sole discretion.</p>

            <p>9. &nbsp;	<b><u>Notices.</u></b>  All notices or other communications required or permitted to be given hereunder shall be (as elected by the person giving such notice): (a) personally delivered; (b) transmitted by postage prepaid registered mail; or (c) transmitted by commercial courier, to the Parties at their respective addresses set forth above. Except as otherwise specified herein, all notices and other communications shall be deemed to have been given on the date of receipt if delivered personally, three (3) days after posting if transmitted by mail, or two (2) days after transmission if transmitted by courier, whichever shall first occur. Any Party hereto may change its address for purposes hereof by written notice to the other Party.</p>

            <p>10. &nbsp;	<b><u>Miscellaneous.</u></b></p>

            <p class="pl-5 pr-5">a. &nbsp;	This Agreement constitutes the entire understanding of the Parties concerning the subject matter hereof, and supersedes all prior agreements and understandings, whether written, oral or otherwise, between the Parties, and may be altered or amended only in a writing signed by both Parties. </p>
            <p class="pl-5 pr-5">b. &nbsp;	Except as otherwise expressly provided herein, no purported waiver by any Party of any breach by the other Party of its obligations, representations, warranties, agreements or covenants hereunder shall be effective unless made in a writing, and no failure to pursue or elect any remedy with respect to any default under or breach of any provisions of this Agreement shall be deemed to be a waiver of any subsequent, similar or different default or breach. </p>
            <p class="pl-5 pr-5">c. &nbsp;	The Parties to this Agreement agree to make, execute, and deliver or cause to be made, executed, and delivered to the requesting Party any other instruments and to take any other actions as the requesting Party may reasonably require to carry out the terms of this Agreement and the transactions contemplated by this Agreement.  </p>
            <p class="pl-5 pr-5">d. &nbsp;	The persons signing this Agreement represent and warrant that they have the necessary power, consent, and authority to execute and deliver this Agreement on behalf of each of the Parties. </p> 
            <p class="pl-5 pr-5">e. &nbsp;	This Agreement is a negotiated document and shall be deemed to have been drafted jointly by the Parties, and no rule of construction or interpretation shall apply against any particular Party based on a contention that the Agreement was drafted by one of the Parties including, but not limited to, Section 1654 California Civil Code, the provisions of which are hereby waived. This Agreement shall be construed and interpreted in a neutral manner.  </p>
            <p class="pl-5 pr-5">f. &nbsp;	If any provision or portion of this Agreement is held by a court of competent jurisdiction to be invalid or unenforceable, the remaining provisions will nevertheless continue in full force and effect without being impaired or invalidated in any way; provided, however, that there shall be deemed to be made in any invalid or unenforceable provision or portion of an invalid or unenforceable provision any minor changes, and only those minor changes, as are necessary to make it valid and enforceable.</p>
            <p>11. &nbsp;	<b><u>Execution in Counterparts</u>.</b>  This Agreement may be executed in any number of counterparts and by each Party to the Agreement on separate counterparts, each of which when so executed and delivered will be deemed an original and all of which taken together will constitute but one and the same instrument.</p>

            IN WITNESS WHEREOF, the Parties hereto have executed this Agreement as of [<i style="background-color: yellow;">insert date</i>].

        </div>
                
            </div>
        </div>
    </section>
</div> *}
{include file="/common/footer-1.tpl" nocache}
