<!-- ===================== start change by divyesh (added) ===================== -->
{include file="/admincp/header.tpl" nocache}

<div class="container-fluid">

    <div class="row">
        <div class="col-lg-12" style="margin-top:2%;">

            <ol class="breadcrumb">
                <li class="active" style=" text-transform: capitalize;">
                    {$action} Generate
                    code
                </li>
            </ol>
        </div>
    </div>

    {if $stat_msg !=''}
    {if $stat_msg_type =='alert-success'}
    <div class="alert {$stat_msg_type}">
        <strong>Saved!</strong>
        {$stat_msg}
    </div>
    {/if}
    {/if}


    {if $stat_msg !=''}
    {if $stat_msg_type =='alert-danger'}
    <div class="alert {$stat_msg_type}">
        <strong>Error!</strong>{$stat_msg}
    </div>
    {/if}
    {/if}


    <form action="{$config.url}/{$loged.adminUrl}/consultant_code/save" method="GET" data-parsley-validate
        enctype="multipart/form-data">
        <div class="row">
<input class="form-control" value="{$id}" id="id" name="id" type="hidden">
            <div class="col-lg-12">
                <div class="col-lg-3">
                    <div class="form-group">
                        <label>Username :</label>
                        <input class="form-control" data-parsley-trigger="change focusout" placeholder="Enter Username"
                            value="{$name}" id="name" name="name" required>
                        <span id="name-check-err" class="err-message"></span>
                    </div>
                </div>

                <div class="col-lg-3">
                    <label>Email :</label>
                    <div class="form-group">
                        <input type="text" required value="{$email}" data-parsley-trigger="change focusout" name="email"
                            data-parsley-type="email" placeholder="Email Address">
                        <span id="email-check-err" class="err-message"></span>
                    </div>
                </div>

                <div class="col-lg-3">
                    <label>Consultant Code :</label>
                    <div class="form-group">
                        <input type="text" readonly value="{$autoGeneratedCode}" name="sc_code"
                            placeholder="consultant code">
                    </div>
                </div>

                <div class="col-lg-3">
                    <label>&nbsp</label>
                    <div class="form-group ">
                        <input class="btn  btn-success" type="submit" value="Submit">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{include file="/admincp/footer.tpl" nocache}
<script src="{$config['externaljs']}scripts.js" type="text/javascript"></script>

<script language="javascript" type="text/javascript">
    
    var initValues = {};

    var initValues = '{$mcats}'.split(',');
    {
        function checkEmailExist(email) {
            //console.log(email);
            if (email != '{$users.email}') {
                data = {
                    email: email
                };
                $.ajax({
                    datatype: 'json',
                    type: "POST",
                    url: "/register/check_email_exist",
                    data: data,
                    success: function (html) {
                        //console.log(html);
                        if (html.status) {
                            $('#divExisteEailReg').css('display', 'none');
                        } else {
                            $('#email').val('');
                            $('#divExisteEailReg').css('display', 'block');
                        }
                    }
                });
            } else {
                return true;
            }
        }
    }
</script>
<!-- ===================== end change by divyesh (added) ===================== -->